/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gradleproject2;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class NewJFrame extends javax.swing.JFrame {

    
    /**
     * Creates new form NewJFrame
     */
    
        int Id=1;
        int row=0;
       // double Total =0.0; //will bbe replaced 
        //int row2 =5;
       
        
         
        Invoice n[]=new Invoice[5];
 
          
         
    
    public NewJFrame() {
        initComponents();
      /*test data  n[0] =new Invoice(1,"11-2-2020","Ali");
n[0].addinvoceItem("mobile",3200.0,1);
n[0].addinvoceItem("Cover",20.0,2);
n[0].addinvoceItem("Headphone",20.0,2);
n[1] =new Invoice(2,"13-2-2020","Ali");
n[1].addinvoceItem("laptop",4000.0,1);
n[1].addinvoceItem("Mouse",35.0,2);*/
     

    }
      /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("invoice Number");

        jLabel2.setText("0");

        jLabel3.setText("invoice Date");

        jLabel4.setText("Customer Name");

        jLabel5.setText("Tota amount");

        jLabel6.setText("0");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "", null, null, null},
                {null, "", null, null, null},
                {null, "", null, null, null},
                {null, "", null, null, null},
                {null, "", null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No.", "Item Name", "Item Price ", "Count", "Item total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setToolTipText("invoice Item ");
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jButton1)
                .addGap(79, 79, 79)
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField3)))
                        .addGap(0, 55, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jButton3.setText("Create new Invoice");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Delete Invoice");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "", "", null},
                {null, "", "", null},
                {null, "", null, null},
                {null, "", null, null}
            },
            new String [] {
                "No.", "Date", "Customer", "ToTal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setToolTipText("invoice Item ");
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel7.setText("Invoce table");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(107, 107, 107))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem1.setText("load File");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Save File");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int Erow = jTable1.getEditingRow();
       // get selected Row id 
        int sr=jTable2.getSelectedRow();
          
           //read id of invice
        int inviceno= (int)jTable2.getValueAt(sr,0);
        // inovice aray of inviceno
        for (int i=0 ;i<=Erow;i++){
        
         String ItemName= String.valueOf(jTable1.getValueAt(i, 1));
         double ItemPrice= Double.parseDouble(String.valueOf(jTable1.getValueAt(i, 2)));
         int C= Integer.parseInt(String.valueOf(jTable1.getValueAt(i, 3)));
         // add item method 
         n[inviceno-1].addinvoceItem(ItemName,ItemPrice,C);
        }
        // view new total in invoice table 
        jTable2.setValueAt(n[inviceno-1].Total, --row, 3);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int rowIndexes[]={0,1,2,3,4,5};
          if (jTable1.isEditing()) {
            int[] selection = jTable1.getSelectedRows();
            jTable1.getCellEditor().cancelCellEditing();
            if (selection.length > 0) {
             jTable1.getSelectionModel().setValueIsAdjusting(true);
        try {
            jTable1.clearSelection();
            for (int row : rowIndexes) {
                jTable1.addRowSelectionInterval(row, row);
            }
            if (jTable1.getCellSelectionEnabled()) {
                jTable1.setColumnSelectionInterval(0,
                        jTable1.getColumnCount() - 1);
            }
        } finally {
            jTable1.getSelectionModel().setValueIsAdjusting(false);
        }
           // }
        
            }
          }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
       
         JOptionPane.showMessageDialog(null, "please choose InvoiceHeader.csv file");
        int i=jFileChooser1.showOpenDialog(this);
        if(i==jFileChooser1.APPROVE_OPTION){    
        File f=jFileChooser1.getSelectedFile(); 
        
        String filepath=f.getPath();
       
        
        try{  
        BufferedReader br=new BufferedReader(new FileReader(filepath));    
        String s1="";                         
        while((s1=br.readLine())!=null){    
        String invioceData[]=  s1.split(",");
        int No =Integer.parseInt(invioceData[0]);
         String Date=invioceData[1];
         String CustomerName=invioceData[2];
         // create object of the first line
         n[Id-1] =new Invoice(No,Date,CustomerName);
          // increase row and id 
          // view in invioce Table after we get 2 files 
          jTable2.setValueAt( n[Id-1].InvoiceNo, row, 0);
          jTable2.setValueAt(n[Id-1].InvoiceDate, row, 1);
          jTable2.setValueAt(n[Id-1].InvoiceCustomerName, row, 2);
          // view total 
          // incre row
          row++;
          Id++;
        }    
            
        br.close();    
        }catch (Exception ex) {ex.printStackTrace();  }
        }
        JOptionPane.showMessageDialog(null, "please choose InvoiceLine.csv file");
        i=jFileChooser1.showOpenDialog(this);
        if(i==jFileChooser1.APPROVE_OPTION){    
        File f=jFileChooser1.getSelectedFile(); 
        
        String filepath=f.getPath();
       
        
        try{  
        BufferedReader br=new BufferedReader(new FileReader(filepath));    
        String s1="";                         
        while((s1=br.readLine())!=null){    
        String invioceData[]=  s1.split(",");
        int No =Integer.parseInt(invioceData[0]);
         String Name=invioceData[1];
         double Price=Double.parseDouble(invioceData[2]);
         int C =Integer.parseInt(invioceData[3]);
         double totalItem= Price* C;
         // create object of the item 
       n[No-1].addinvoceItem(Name,Price,C);
          //  
          
          // view total in invoice table  
          // incre row
       
        } 
        for (int k=0;i<Id ;k++){
         jTable2.setValueAt( n[k].Total, k, 3);
        }
            
        br.close();    
        }catch (Exception ex) {ex.printStackTrace();  }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        ///clear table

        /*  for(int i=0 ;i<7;i++){
            for (int j=0 ;j<5;j++){
                if(j==4){
                    jTable1.setValueAt( 0.0, i, j);
                }
                else{
                    jTable1.setValueAt( " ", i, j);}
            }

        }*/

        int sr=jTable2.getSelectedRow();

        //read id of invice
        int inviceno= (int)jTable2.getValueAt(sr,0);
        // inovice aray of inviceno
        //get invoce data and show them
        jLabel2.setText(String.valueOf(inviceno));
        jTextField2.setText(n[inviceno-1].InvoiceDate);
        jTextField3.setText(n[inviceno-1].InvoiceCustomerName);
        jLabel6.setText(String.valueOf(n[inviceno-1].Total));
        for(int i=0 ;i<n[inviceno-1].Noitem;i++ ){
            jTable1.setValueAt(n[inviceno-1].InvoiceNo, i, 0);
            jTable1.setValueAt(n[inviceno-1].InvoiceItems[i].ItemName, i, 1);
            jTable1.setValueAt(n[inviceno-1].InvoiceItems[i].ItemPrice, i, 2);
            jTable1.setValueAt(n[inviceno-1].InvoiceItems[i].Count, i, 3);
            jTable1.setValueAt(n[inviceno-1].InvoiceItems[i].ItemTotal, i, 4);}
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int colum =0;
        // crete invoice object 
        String Date =jTextField2.getText();
        String custname =jTextField3.getText();
         n[Id-1] =new Invoice(Id,Date,custname);
        //set table Data 
         jTable2.setValueAt(Id, row, colum);
                              
           jTable2.setValueAt( n[Id-1].InvoiceDate, row, ++colum);
            jTable2.setValueAt( n[Id-1].InvoiceCustomerName, row, ++colum);
            jTable2.setValueAt( n[Id-1].Total, row, ++colum);               
     

         

       
          
        Id++;
        row++;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         int i=jFileChooser1.showOpenDialog(this);
        if(i==jFileChooser1.APPROVE_OPTION){    
        File f=jFileChooser1.getSelectedFile(); 
        
        String filepath=f.getPath();
       
         // if we choose heeder we will read and append in header file else we will append in line 
        try{  
        BufferedWriter br=new  BufferedWriter(new FileWriter(filepath));
        
        // get Data from array with last 
        
       for(int j=0 ;j<=Id;j++){
         // String no=String.valueOf(n[j].InvoiceNo); 
             
            // br.newLine();
        br.append(String.valueOf(n[j].InvoiceNo+","+n[j].InvoiceDate+","+n[j].InvoiceCustomerName));
       
         br.newLine();
       }
        br.close();      
        
        }
        catch (Exception ex) {ex.printStackTrace();} 
       
        
        }
        i=jFileChooser1.showOpenDialog(this);
        if(i==jFileChooser1.APPROVE_OPTION){    
        File f=jFileChooser1.getSelectedFile(); 
        
        String filepath=f.getPath();
       
         // if we choose heeder we will read and append in header file else we will append in line 
        try{  
        BufferedWriter br=new  BufferedWriter(new FileWriter(filepath));
        
        // get Data from array with last 
       
       for(int j=0 ;j<=Id;j++){
          
             
            // save invoice line;
            for(int k=0 ;k<n[j].Noitem;k++){
        br.append(String.valueOf(n[j].InvoiceNo+","+n[j].InvoiceItems[k].ItemName+","+n[j].InvoiceItems[k].ItemPrice+","+n[j].InvoiceItems[k].Count));
        br.newLine();
            }
         
       }
        br.close();      
        
        }
        catch (Exception ex) {ex.printStackTrace();  }  
        
        }
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int deleter=jTable2.getSelectedRow();
       
           jTable2.setValueAt( " ", deleter, 0);
           jTable2.setValueAt( " ", deleter,1);
           jTable2.setValueAt(" ",  deleter, 2);
           jTable2.setValueAt( 0.0, deleter, 3);
           Id--;
           row--;
    }//GEN-LAST:event_jButton4ActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
